import type { Job } from '@/types'

export const JOBS_MOCK_DATA: Job[] = [
  {
    id: 'job-1',
    title: 'Senior Frontend Engineer',
    department: 'Engineering',
    location: 'San Francisco, CA',
    experience: '5+ years',
    status: 'open',
    employmentType: 'full_time',
    salaryMin: 150000,
    salaryMax: 190000,
    description: 'Build scalable hiring experiences with React and TypeScript.',
    requirements: ['5+ years React', 'TypeScript', 'System design'],
    candidateCount: 24,
    hiringManagerId: 'user-2',
    hiringManagerName: 'Jordan Lee',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-05-10T14:30:00Z',
  },
  {
    id: 'job-2',
    title: 'Product Designer',
    department: 'Design',
    location: 'Remote',
    experience: '3–5 years',
    status: 'open',
    employmentType: 'full_time',
    salaryMin: 120000,
    salaryMax: 155000,
    description: 'Shape intuitive workflows for recruiters and hiring managers.',
    requirements: ['Figma', 'Design systems', 'User research'],
    candidateCount: 18,
    hiringManagerId: 'user-3',
    hiringManagerName: 'Sam Patel',
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-05-08T11:00:00Z',
  },
  {
    id: 'job-3',
    title: 'DevOps Engineer',
    department: 'Engineering',
    location: 'New York, NY',
    experience: '4+ years',
    status: 'paused',
    employmentType: 'full_time',
    salaryMin: 140000,
    salaryMax: 175000,
    description: 'Own CI/CD pipelines and cloud infrastructure.',
    requirements: ['AWS', 'Kubernetes', 'Terraform'],
    candidateCount: 12,
    hiringManagerId: 'user-2',
    hiringManagerName: 'Jordan Lee',
    createdAt: '2026-03-12T08:00:00Z',
    updatedAt: '2026-04-20T16:00:00Z',
  },
  {
    id: 'job-4',
    title: 'Data Analyst',
    department: 'Analytics',
    location: 'Austin, TX',
    experience: '2–4 years',
    status: 'open',
    employmentType: 'full_time',
    salaryMin: 90000,
    salaryMax: 120000,
    description: 'Analyze hiring metrics and build reporting dashboards.',
    requirements: ['SQL', 'Python', 'Tableau'],
    candidateCount: 9,
    hiringManagerId: 'user-1',
    hiringManagerName: 'Alex Morgan',
    createdAt: '2026-03-20T10:00:00Z',
    updatedAt: '2026-05-15T09:00:00Z',
  },
  {
    id: 'job-5',
    title: 'Technical Recruiter',
    department: 'People Operations',
    location: 'Remote',
    experience: '3+ years',
    status: 'draft',
    employmentType: 'full_time',
    description: 'Source and engage top engineering talent.',
    requirements: ['Technical sourcing', 'ATS experience'],
    candidateCount: 0,
    hiringManagerId: 'user-1',
    hiringManagerName: 'Alex Morgan',
    createdAt: '2026-04-05T14:00:00Z',
    updatedAt: '2026-04-05T14:00:00Z',
  },
  {
    id: 'job-6',
    title: 'Backend Engineer',
    department: 'Engineering',
    location: 'Seattle, WA',
    experience: '5+ years',
    status: 'open',
    employmentType: 'full_time',
    salaryMin: 145000,
    salaryMax: 185000,
    description: 'Design and build APIs powering the HireFlow platform.',
    requirements: ['Node.js', 'PostgreSQL', 'Microservices'],
    candidateCount: 31,
    hiringManagerId: 'user-2',
    hiringManagerName: 'Jordan Lee',
    createdAt: '2026-04-10T08:00:00Z',
    updatedAt: '2026-05-18T11:00:00Z',
  },
  {
    id: 'job-7',
    title: 'Marketing Manager',
    department: 'Marketing',
    location: 'Chicago, IL',
    experience: '6+ years',
    status: 'closed',
    employmentType: 'full_time',
    salaryMin: 110000,
    salaryMax: 140000,
    description: 'Lead employer branding and recruitment marketing campaigns.',
    requirements: ['B2B marketing', 'Content strategy'],
    candidateCount: 15,
    hiringManagerId: 'user-3',
    hiringManagerName: 'Sam Patel',
    createdAt: '2025-11-01T09:00:00Z',
    updatedAt: '2026-02-28T16:00:00Z',
  },
  {
    id: 'job-8',
    title: 'QA Engineer',
    department: 'Engineering',
    location: 'Remote',
    experience: '3–5 years',
    status: 'open',
    employmentType: 'full_time',
    salaryMin: 100000,
    salaryMax: 130000,
    description: 'Ensure quality across the HireFlow product suite.',
    requirements: ['Playwright', 'CI/CD', 'Test automation'],
    candidateCount: 7,
    hiringManagerId: 'user-2',
    hiringManagerName: 'Jordan Lee',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-19T08:00:00Z',
  },
  {
    id: 'job-9',
    title: 'Sales Development Rep',
    department: 'Sales',
    location: 'Boston, MA',
    experience: '1–2 years',
    status: 'paused',
    employmentType: 'full_time',
    salaryMin: 55000,
    salaryMax: 75000,
    description: 'Generate pipeline for HireFlow enterprise accounts.',
    requirements: ['Outbound sales', 'CRM tools'],
    candidateCount: 4,
    hiringManagerId: 'user-3',
    hiringManagerName: 'Sam Patel',
    createdAt: '2026-05-05T12:00:00Z',
    updatedAt: '2026-05-12T10:00:00Z',
  },
  {
    id: 'job-10',
    title: 'Customer Success Manager',
    department: 'Customer Success',
    location: 'Remote',
    experience: '4+ years',
    status: 'draft',
    employmentType: 'full_time',
    description: 'Onboard and retain HireFlow enterprise customers.',
    requirements: ['SaaS CS', 'Account management'],
    candidateCount: 0,
    hiringManagerId: 'user-1',
    hiringManagerName: 'Alex Morgan',
    createdAt: '2026-05-18T09:00:00Z',
    updatedAt: '2026-05-18T09:00:00Z',
  },
]

export type { JobFormValues as JobFormData } from '@/lib/validations/jobSchema'
export { jobFormDefaultValues as EMPTY_JOB_FORM } from '@/lib/validations/jobSchema'
