import type { Candidate } from '@/types'

export const CANDIDATES_MOCK_DATA: Candidate[] = [
  {
    id: 'cand-1',
    firstName: 'Maya',
    lastName: 'Chen',
    email: 'maya.chen@email.com',
    phone: '+1 415-555-0101',
    pipelineStage: 'technical_interview',
    jobId: 'job-1',
    jobTitle: 'Senior Frontend Engineer',
    location: 'Oakland, CA',
    experienceYears: 7,
    skills: ['React', 'TypeScript', 'GraphQL'],
    rating: 4.5,
    appliedAt: '2026-04-28T12:00:00Z',
    updatedAt: '2026-05-18T09:00:00Z',
  },
  {
    id: 'cand-2',
    firstName: 'David',
    lastName: 'Okonkwo',
    email: 'david.o@email.com',
    phone: '+1 512-555-0202',
    pipelineStage: 'screening',
    jobId: 'job-1',
    jobTitle: 'Senior Frontend Engineer',
    location: 'Austin, TX',
    experienceYears: 5,
    skills: ['React', 'Next.js', 'Tailwind'],
    rating: 4,
    appliedAt: '2026-05-02T08:00:00Z',
    updatedAt: '2026-05-15T14:00:00Z',
  },
  {
    id: 'cand-3',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@email.com',
    phone: '+1 206-555-0303',
    pipelineStage: 'offer',
    jobId: 'job-2',
    jobTitle: 'Product Designer',
    location: 'Seattle, WA',
    experienceYears: 6,
    skills: ['Figma', 'Prototyping', 'Accessibility'],
    rating: 4.8,
    appliedAt: '2026-04-10T10:00:00Z',
    updatedAt: '2026-05-19T11:30:00Z',
  },
  {
    id: 'cand-4',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'j.wilson@email.com',
    phone: '+1 312-555-0404',
    pipelineStage: 'applied',
    jobId: 'job-2',
    jobTitle: 'Product Designer',
    location: 'Chicago, IL',
    experienceYears: 3,
    skills: ['UI Design', 'Illustration'],
    appliedAt: '2026-05-19T16:00:00Z',
    updatedAt: '2026-05-19T16:00:00Z',
  },
  {
    id: 'cand-5',
    firstName: 'Elena',
    lastName: 'Vasquez',
    email: 'elena.v@email.com',
    phone: '+1 718-555-0505',
    pipelineStage: 'hired',
    jobId: 'job-3',
    jobTitle: 'DevOps Engineer',
    location: 'Brooklyn, NY',
    experienceYears: 8,
    skills: ['AWS', 'Docker', 'CI/CD'],
    rating: 5,
    appliedAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-04-30T10:00:00Z',
  },
  {
    id: 'cand-6',
    firstName: 'Alex',
    lastName: 'Kim',
    email: 'alex.kim@email.com',
    phone: '+1 646-555-0606',
    pipelineStage: 'screening',
    jobId: 'job-6',
    jobTitle: 'Backend Engineer',
    location: 'New York, NY',
    experienceYears: 4,
    skills: ['Node.js', 'PostgreSQL'],
    rating: 3.8,
    appliedAt: '2026-05-10T11:00:00Z',
    updatedAt: '2026-05-17T09:00:00Z',
  },
  {
    id: 'cand-7',
    firstName: 'Sofia',
    lastName: 'Martinez',
    email: 'sofia.m@email.com',
    pipelineStage: 'applied',
    jobId: 'job-4',
    jobTitle: 'Data Analyst',
    location: 'Denver, CO',
    experienceYears: 2,
    skills: ['SQL', 'Python'],
    appliedAt: '2026-05-20T14:00:00Z',
    updatedAt: '2026-05-20T14:00:00Z',
  },
  {
    id: 'cand-8',
    firstName: 'Ryan',
    lastName: 'Foster',
    email: 'ryan.foster@email.com',
    phone: '+1 617-555-0808',
    pipelineStage: 'technical_interview',
    jobId: 'job-8',
    jobTitle: 'QA Engineer',
    location: 'Boston, MA',
    experienceYears: 5,
    skills: ['Playwright', 'Jest'],
    rating: 4.2,
    appliedAt: '2026-05-08T10:00:00Z',
    updatedAt: '2026-05-16T15:00:00Z',
  },
  {
    id: 'cand-9',
    firstName: 'Nina',
    lastName: 'Patel',
    email: 'nina.patel@email.com',
    phone: '+1 408-555-0909',
    pipelineStage: 'rejected',
    jobId: 'job-1',
    jobTitle: 'Senior Frontend Engineer',
    location: 'San Jose, CA',
    experienceYears: 1,
    skills: ['JavaScript', 'CSS'],
    rating: 2.5,
    appliedAt: '2026-04-01T09:00:00Z',
    updatedAt: '2026-04-25T10:00:00Z',
  },
  {
    id: 'cand-10',
    firstName: 'Marcus',
    lastName: 'Johnson',
    email: 'marcus.j@email.com',
    phone: '+1 305-555-1010',
    pipelineStage: 'offer',
    jobId: 'job-6',
    jobTitle: 'Backend Engineer',
    location: 'Miami, FL',
    experienceYears: 9,
    skills: ['Go', 'Kubernetes', 'gRPC'],
    rating: 4.9,
    appliedAt: '2026-03-15T08:00:00Z',
    updatedAt: '2026-05-18T12:00:00Z',
  },
  {
    id: 'cand-11',
    firstName: 'Lily',
    lastName: 'Nguyen',
    email: 'lily.nguyen@email.com',
    phone: '+1 213-555-1111',
    pipelineStage: 'screening',
    jobId: 'job-2',
    jobTitle: 'Product Designer',
    location: 'Los Angeles, CA',
    experienceYears: 4,
    skills: ['Figma', 'Motion design'],
    rating: 4.1,
    appliedAt: '2026-05-12T13:00:00Z',
    updatedAt: '2026-05-19T08:00:00Z',
  },
  {
    id: 'cand-12',
    firstName: 'Tom',
    lastName: 'Bradley',
    email: 'tom.bradley@email.com',
    pipelineStage: 'applied',
    jobId: 'job-8',
    jobTitle: 'QA Engineer',
    location: 'Portland, OR',
    experienceYears: 0,
    skills: ['Manual testing'],
    appliedAt: '2026-05-21T08:00:00Z',
    updatedAt: '2026-05-21T08:00:00Z',
  },
]

export type { ExperienceFilter } from '@/constants'
export {
  CANDIDATE_EXPERIENCE_FILTER_OPTIONS as EXPERIENCE_FILTER_OPTIONS,
  matchesExperienceFilter,
} from '@/constants'
