import type { ActivityLogEntry } from '@/types/activityLog'

export const ACTIVITY_LOG_MOCK_DATA: ActivityLogEntry[] = [
  {
    id: 'act-1',
    action: 'candidate_created',
    title: 'Candidate Created',
    description: 'James Wilson applied for Product Designer',
    actor: 'System',
    candidateId: 'cand-4',
    candidateName: 'James Wilson',
    jobTitle: 'Product Designer',
    timestamp: '2026-05-21T08:00:00Z',
  },
  {
    id: 'act-2',
    action: 'feedback_submitted',
    title: 'Feedback Submitted',
    description: 'Phone screen feedback recorded — positive recommendation',
    actor: 'Alex Morgan',
    candidateId: 'cand-4',
    candidateName: 'James Wilson',
    jobTitle: 'Product Designer',
    timestamp: '2026-05-20T09:30:00Z',
  },
  {
    id: 'act-3',
    action: 'stage_change',
    title: 'Moved to Screening',
    description: 'David Okonkwo advanced from Applied to Screening',
    actor: 'Jordan Lee',
    candidateId: 'cand-2',
    candidateName: 'David Okonkwo',
    jobTitle: 'Senior Frontend Engineer',
    timestamp: '2026-05-20T11:00:00Z',
  },
  {
    id: 'act-4',
    action: 'offer_released',
    title: 'Offer Released',
    description: 'Formal offer letter sent for Product Designer role',
    actor: 'Alex Morgan',
    candidateId: 'cand-3',
    candidateName: 'Priya Sharma',
    jobTitle: 'Product Designer',
    timestamp: '2026-05-19T10:00:00Z',
  },
  {
    id: 'act-5',
    action: 'interview_scheduled',
    title: 'Interview Scheduled',
    description: 'Technical interview with Maya Chen — 60 min video call',
    actor: 'Jordan Lee',
    candidateId: 'cand-1',
    candidateName: 'Maya Chen',
    jobTitle: 'Senior Frontend Engineer',
    timestamp: '2026-05-19T14:00:00Z',
  },
  {
    id: 'act-6',
    action: 'feedback_submitted',
    title: 'Feedback Submitted',
    description: 'Technical round feedback — strong yes recommendation',
    actor: 'Sam Patel',
    candidateId: 'cand-1',
    candidateName: 'Maya Chen',
    jobTitle: 'Senior Frontend Engineer',
    timestamp: '2026-05-18T16:30:00Z',
  },
  {
    id: 'act-7',
    action: 'stage_change',
    title: 'Moved to Technical Interview',
    description: 'Maya Chen advanced to Technical Interview stage',
    actor: 'Jordan Lee',
    candidateId: 'cand-1',
    candidateName: 'Maya Chen',
    jobTitle: 'Senior Frontend Engineer',
    timestamp: '2026-05-18T09:00:00Z',
  },
  {
    id: 'act-8',
    action: 'candidate_hired',
    title: 'Candidate Hired',
    description: 'Elena Vasquez accepted offer — start date confirmed',
    actor: 'Alex Morgan',
    candidateId: 'cand-5',
    candidateName: 'Elena Vasquez',
    jobTitle: 'DevOps Engineer',
    timestamp: '2026-05-17T10:00:00Z',
  },
  {
    id: 'act-9',
    action: 'job_created',
    title: 'Job Created',
    description: 'New job posting published: QA Engineer',
    actor: 'Alex Morgan',
    jobTitle: 'QA Engineer',
    timestamp: '2026-05-16T08:00:00Z',
  },
  {
    id: 'act-10',
    action: 'candidate_created',
    title: 'Candidate Created',
    description: 'Ryan Foster applied for QA Engineer',
    actor: 'System',
    candidateId: 'cand-8',
    candidateName: 'Ryan Foster',
    jobTitle: 'QA Engineer',
    timestamp: '2026-05-15T10:00:00Z',
  },
  {
    id: 'act-11',
    action: 'stage_change',
    title: 'Moved to Screening',
    description: 'Alex Kim advanced from Applied to Screening',
    actor: 'Jordan Lee',
    candidateId: 'cand-6',
    candidateName: 'Alex Kim',
    jobTitle: 'Backend Engineer',
    timestamp: '2026-05-14T11:00:00Z',
  },
  {
    id: 'act-12',
    action: 'feedback_submitted',
    title: 'Feedback Submitted',
    description: 'Panel interview feedback for Marcus Johnson',
    actor: 'Jordan Lee',
    candidateId: 'cand-10',
    candidateName: 'Marcus Johnson',
    jobTitle: 'Backend Engineer',
    timestamp: '2026-05-13T15:00:00Z',
  },
  {
    id: 'act-13',
    action: 'candidate_rejected',
    title: 'Candidate Rejected',
    description: 'Did not meet senior-level requirements',
    actor: 'Jordan Lee',
    candidateId: 'cand-9',
    candidateName: 'Nina Patel',
    jobTitle: 'Senior Frontend Engineer',
    timestamp: '2026-05-12T10:00:00Z',
  },
  {
    id: 'act-14',
    action: 'offer_accepted',
    title: 'Offer Accepted',
    description: 'Priya Sharma signed offer letter',
    actor: 'System',
    candidateId: 'cand-3',
    candidateName: 'Priya Sharma',
    jobTitle: 'Product Designer',
    timestamp: '2026-05-11T14:00:00Z',
  },
  {
    id: 'act-15',
    action: 'email_sent',
    title: 'Email Sent',
    description: 'Interview confirmation sent to David Okonkwo',
    actor: 'Jordan Lee',
    candidateId: 'cand-2',
    candidateName: 'David Okonkwo',
    timestamp: '2026-05-10T09:00:00Z',
  },
  {
    id: 'act-16',
    action: 'note_added',
    title: 'Note Added',
    description: 'Recruiter note: strong portfolio, schedule panel review',
    actor: 'Sam Patel',
    candidateId: 'cand-11',
    candidateName: 'Lily Nguyen',
    jobTitle: 'Product Designer',
    timestamp: '2026-05-09T16:00:00Z',
  },
  {
    id: 'act-17',
    action: 'candidate_created',
    title: 'Candidate Created',
    description: 'Maya Chen applied for Senior Frontend Engineer',
    actor: 'System',
    candidateId: 'cand-1',
    candidateName: 'Maya Chen',
    jobTitle: 'Senior Frontend Engineer',
    timestamp: '2026-05-08T12:00:00Z',
  },
  {
    id: 'act-18',
    action: 'job_created',
    title: 'Job Created',
    description: 'New job posting published: Backend Engineer',
    actor: 'Alex Morgan',
    jobTitle: 'Backend Engineer',
    timestamp: '2026-05-05T08:00:00Z',
  },
  {
    id: 'act-19',
    action: 'stage_change',
    title: 'Moved to HR Round',
    description: 'Priya Sharma advanced to HR Round',
    actor: 'Alex Morgan',
    candidateId: 'cand-3',
    candidateName: 'Priya Sharma',
    jobTitle: 'Product Designer',
    timestamp: '2026-05-04T11:00:00Z',
  },
  {
    id: 'act-20',
    action: 'interview_scheduled',
    title: 'Interview Scheduled',
    description: 'Panel interview with Priya Sharma — 90 min',
    actor: 'Sam Patel',
    candidateId: 'cand-3',
    candidateName: 'Priya Sharma',
    jobTitle: 'Product Designer',
    timestamp: '2026-05-02T14:00:00Z',
  },
]
