import type { FeedbackListItem } from '@/types/feedback'

export const FEEDBACK_MOCK_DATA: FeedbackListItem[] = [
  {
    id: 'fb-1',
    candidateId: 'cand-1',
    candidateName: 'Maya Chen',
    jobTitle: 'Senior Frontend Engineer',
    interviewer: 'Jordan Lee',
    interviewerRole: 'Engineering Manager',
    interviewType: 'Phone Screen',
    date: '2026-05-10T14:00:00Z',
    rating: 4,
    recommendation: 'yes',
    comment:
      'Strong communication skills and clear examples of past work. Demonstrated solid understanding of React patterns and team collaboration.',
  },
  {
    id: 'fb-2',
    candidateId: 'cand-1',
    candidateName: 'Maya Chen',
    jobTitle: 'Senior Frontend Engineer',
    interviewer: 'Sam Patel',
    interviewerRole: 'Senior Engineer',
    interviewType: 'Technical Interview',
    date: '2026-05-15T16:00:00Z',
    rating: 4.5,
    recommendation: 'strong_yes',
    comment:
      'Excellent problem-solving approach. Completed the coding exercise efficiently with clean, maintainable code. Would recommend moving forward.',
  },
  {
    id: 'fb-3',
    candidateId: 'cand-3',
    candidateName: 'Priya Sharma',
    jobTitle: 'Product Designer',
    interviewer: 'Alex Morgan',
    interviewerRole: 'Head of People',
    interviewType: 'Culture Fit',
    date: '2026-05-18T11:00:00Z',
    rating: 5,
    recommendation: 'strong_yes',
    comment:
      'Great alignment with company values. Enthusiastic about the role and asked thoughtful questions about team structure and growth.',
  },
  {
    id: 'fb-4',
    candidateId: 'cand-2',
    candidateName: 'David Okonkwo',
    jobTitle: 'Senior Frontend Engineer',
    interviewer: 'Jordan Lee',
    interviewerRole: 'Engineering Manager',
    interviewType: 'Phone Screen',
    date: '2026-05-12T10:00:00Z',
    rating: 3.5,
    recommendation: 'neutral',
    comment:
      'Good technical background but answers lacked depth on system design. Worth a follow-up technical round before deciding.',
  },
  {
    id: 'fb-5',
    candidateId: 'cand-8',
    candidateName: 'Ryan Foster',
    jobTitle: 'QA Engineer',
    interviewer: 'Sam Patel',
    interviewerRole: 'QA Lead',
    interviewType: 'Technical Interview',
    date: '2026-05-14T15:30:00Z',
    rating: 4.2,
    recommendation: 'yes',
    comment:
      'Solid test automation experience with Playwright. Provided good examples of CI integration and flaky test mitigation strategies.',
  },
  {
    id: 'fb-6',
    candidateId: 'cand-10',
    candidateName: 'Marcus Johnson',
    jobTitle: 'Backend Engineer',
    interviewer: 'Jordan Lee',
    interviewerRole: 'Engineering Manager',
    interviewType: 'Panel Interview',
    date: '2026-05-16T13:00:00Z',
    rating: 4.9,
    recommendation: 'strong_yes',
    comment:
      'Outstanding panel performance. Deep expertise in distributed systems and clear leadership examples from previous roles.',
  },
  {
    id: 'fb-7',
    candidateId: 'cand-9',
    candidateName: 'Nina Patel',
    jobTitle: 'Senior Frontend Engineer',
    interviewer: 'Jordan Lee',
    interviewerRole: 'Engineering Manager',
    interviewType: 'Technical Interview',
    date: '2026-04-20T15:00:00Z',
    rating: 2.5,
    recommendation: 'no',
    comment:
      'Gap in required experience level for this role. Struggled with intermediate React concepts. Recommended for junior positions instead.',
  },
  {
    id: 'fb-8',
    candidateId: 'cand-6',
    candidateName: 'Alex Kim',
    jobTitle: 'Backend Engineer',
    interviewer: 'Sam Patel',
    interviewerRole: 'Senior Engineer',
    interviewType: 'Technical Interview',
    date: '2026-05-17T11:00:00Z',
    rating: 3.8,
    recommendation: 'yes',
    comment:
      'Competent with Node.js and database design. Some gaps in caching strategies but showed willingness to learn and good debugging skills.',
  },
  {
    id: 'fb-9',
    candidateId: 'cand-11',
    candidateName: 'Lily Nguyen',
    jobTitle: 'Product Designer',
    interviewer: 'Alex Morgan',
    interviewerRole: 'Design Lead',
    interviewType: 'Portfolio Review',
    date: '2026-05-19T14:00:00Z',
    rating: 4.1,
    recommendation: 'yes',
    comment:
      'Impressive portfolio with strong case studies. Clear design process and good eye for accessibility. Minor gaps in motion design.',
  },
  {
    id: 'fb-10',
    candidateId: 'cand-4',
    candidateName: 'James Wilson',
    jobTitle: 'Product Designer',
    interviewer: 'Alex Morgan',
    interviewerRole: 'Design Lead',
    interviewType: 'Phone Screen',
    date: '2026-05-20T09:30:00Z',
    rating: 3,
    recommendation: 'neutral',
    comment:
      'Early career designer with potential. Portfolio shows creativity but limited enterprise product experience. Consider for junior role.',
  },
]
